### ISSUE TITLE
一个简洁优雅的模版～请问可否提供“主页文章按updated时间排列”的功能？

### ISSUE THREAD

**Issue by KMdsy** [smile-yan/hexo-theme-heyan#2]

**Comment by smile-yan** [comment]
你好，我这个周六或者周日更新这个功能。感谢反馈 ~

**Comment by smile-yan** [comment]
你好问题已经解决，但是并不是从代码的角度出发，而是通过修改配置文件：
hexo 项目自带的配置文件（而不是主题配置）

```yaml
index_generator:
  path: ''
  per_page: 10
  order_by: -updated
```
最后一行改为 `-updated`。

这样做可以根据更新时间排序、比较简单方便
